version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
  build:
    commands:
      - aws s3 sync ./public_html s3://$S3_BUCKET/ --acl public-read